### ISSUE TITLE
Run CI via GitHub Actions and upload the latest cutting-edge release

### ISSUE THREAD

**Issue by pmq20** [pmq20/ruby-packer#100]

**Comment by bkmgit** [comment]
Thanks for useful software.

Would it be worth getting GitHub actions to also build rubyc for linux from the current repository? Can add this if helpful.

**Comment by bkmgit** [comment]
Latest build of rubyc seems to require libncurses-dev on Ubuntu or ncurses-compat-libs on Fedora to start.

**Comment by pmq20** [comment]
@bkmgit  Sorry for the delayed Reply. I'm maintaining this project only during the weekend recently. Yes I am also planning to let the CI generate a binary as a CI-artifact. Thank you very much for the link! I'm working on it today.

**Comment by pmq20** [comment]
CI is now running on GitHub Actions.

**Comment by pmq20** [comment]
still need to Upload Release Asset

**Comment by bkmgit** [comment]
Can look at this tomorrow if helpful.

**Comment by pmq20** [comment]
@bkmgit Thank you for the help! I have successfully make the Latest Build links below automatically kept up to date with the latest code in master, as long as the tests are passed. Meanwhile, I'll look into the issue of `libtinfo-dev` / `ncurses-compat-libs`.

|                                            | Arch. |                               Latest Build                                    |
|--------------------------------------------|:-----:|-------------------------------------------------------------------------------|
| ![win](resource/win_sm.png)  **Windows**   |  x64  | https://github.com/pmq20/ruby-packer/releases/download/windows-x64/rubyc.exe  |
| ![macOS](resource/apple_sm.png) **macOS**  |  x64  | https://github.com/pmq20/ruby-packer/releases/download/darwin-x64/rubyc       |
| ![linux](resource/linux_sm.png) **Linux**  |  x64  | https://github.com/pmq20/ruby-packer/releases/download/linux-x64/rubyc        |
