### ISSUE TITLE
Cannot download binaries, site is down

### ISSUE THREAD

**Issue by silasb** [pmq20/ruby-packer#105]
Trying to run instructions and noticed that http://enclose.io/rubyc/ is down and we can't download binaries.  Any reason why they are stored in GH releases?

**Comment by bkmgit** [comment]
You can find a binary for linux at:
https://github.com/bkmgit/ruby-packer/releases
Workflow to create this is here:
https://github.com/bkmgit/ruby-packer/blob/master/.github/workflows/build-rubyc.yml

Maybe able to modify for Mac and Windows.

**Comment by pmq20** [comment]
@silasb The site has been restored. I will store them in GH releases (or as GH Actions actifacts) in the future.

Also, thank you @bkmgit for providing an alternative link!

**Comment by pmq20** [comment]
We have decided to use GitHub Actions and GitHub Releases as the auto-packing and auto-updating web services. The Latest Build links in README.md will be kept up to date with the latest code in `master`, as long as all tests are passed. See #100
