### ISSUE TITLE
Massive performance regression

### ISSUE THREAD

**Issue by d4rky-pl** [pmq20/ruby-packer#117]
Upgrading Ruby from 2.4.1 to 2.7.1a is definitely a step in the right direction in terms of future maintainability and compatibility with other gems.

That being said, 2.7.1 has a massive performance regression compared to 2.4.1.
Benchmarking on our internal CLI tool:

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `./ht-0.4.0` | 233.7 ± 4.4 | 226.4 | 238.9 | 1.00 |
| `./ht-2.7.1` | 1105.3 ± 9.3 | 1090.6 | 1118.1 | 4.73 ± 0.10 |

(benchmarked using [hyperfine](https://github.com/sharkdp/hyperfine))

For our tool we don't need the latest version of Ruby but we could really use a version that is fast. Please bring back 0.4.0 to Releases so we can keep using it until Ruby catches up with speed again.

**Comment by pmq20** [comment]
@d4rky-pl Thanks for reporting! I'll have to figure out which part took so long. It might not be Ruby's fault. Let me reproduce it ASAP.

**Comment by d4rky-pl** [comment]
The problem no longer happens with the latest tagged release
