### ISSUE TITLE
`openssl-dir` commandline option is (still) not correctly defined

### ISSUE THREAD

**Issue by saveriomiroddi** [pmq20/ruby-packer#126]
When trying to execute rubyc with the `--openssl-dir=$dir` option, I get an error:

```
$ rubyc --openssl-dir=/etc/ssl $my_script
Traceback (most recent call last):
/__enclose_io_memfs__/local/bin/rubyc:134:in `<main>': needless argument: --openssl-dir=/etc/ssl (OptionParser::NeedlessArgument)
```

Now, this is due to something that was [pointed out in a PR](https://github.com/pmq20/ruby-packer/pull/47#issuecomment-442017875), which, based on [master's content](https://github.com/pmq20/ruby-packer/blob/31609e88c02d8e97aa42dad41af30cba572a2bf6/bin/rubyc#L75), it has been missed.

**Comment by pmq20** [comment]
@saveriomiroddi Thanks for reporting and fixing! This should have been fixed since the PR has been merged.
