### ISSUE TITLE
Pack more files

### ISSUE THREAD

**Issue by samuelintheforest** [pmq20/ruby-packer#148]
Hello! 

My Question is that: How to pack more files into your executable (images and stuff like that). Now it just packs the .rb files only.

Here is an image for comparison
![Comparison](https://user-images.githubusercontent.com/31268252/104366493-c144ff80-5519-11eb-9c48-7787e85031cb.jpg)

(Left one is source and right one is the release)
So anyone know a solution? To pack all the other files as well? (.vs, .fs, .dlls, .jpg, .png), in a way that I obtain just the executable?

Anyway, the outcome is nice and working! (By following learnopengl.com) :
![opengl_ruby](https://user-images.githubusercontent.com/31268252/104367145-afb02780-551a-11eb-8866-f4e2e8e331d9.jpg)

Thank you in advance!
Greetings,
Samuel from Budapest 😁

**Comment by samuelintheforest** [comment]
Okay, eventually I got my project working. 😏
A little demo what Ruby can achive with Opengl: (actually it is faster in real and not that jaggy).
![opengl_demo](https://user-images.githubusercontent.com/31268252/106053649-55eb5800-60eb-11eb-8ab9-2d04fbe6c59b.gif)

**Comment by 367null** [comment]
@samuelintheforest ruby 3.x?
