### ISSUE TITLE
Rename project ruby-compiler to ruby-packer

### ISSUE THREAD

**Issue by slayer** [pmq20/ruby-packer#16]
Hi

As I see, that project does not compile ruby code to machine or byte code, it just packs it.
So it will be honestly to rename project to avoid misrepresentation.

Thanks

**Comment by andy-twosticks** [comment]
Not really my place to agree or disagree -- I'm just another user, and you are entitled to your point of view.

...but, it creates an executable that can be run without installing ruby?

**Comment by slayer** [comment]
Sure. It creates an executable with packed (source) ruby code.
In my youth there was a BASIC language suite that generates a binary of BASIC interpreter with appended zip-archive of source code. Exactly the same idea here.
And this project is not a compiler.

Wikipedia:
_A compiler is computer software that transforms computer code written in one programming language (the source language) into another computer language (the target language). Compilers are a type of translator that support digital devices, primarily computers. The name compiler is primarily used for programs that translate source code from a high-level programming language to a lower level language (e.g., assembly language, object code, or machine code) to create an executable program.[1]_

**Comment by pmq20** [comment]
Thanks @slayer , Good point. This project shalled be named to Ruby Packer now. 

@andy-twosticks Sorry I am too occupied recently to debug your reported issue. Let me do it ASAP. Sorry for the dealy!

**Comment by slayer** [comment]
Thank you
