### ISSUE TITLE
Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by grosser** [pmq20/ruby-packer#18]
maybe because I'm on Yosemite ... but a better error message would be good :)
```
./rubyc help
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/mgrosser/Code/tools/ruco/./rubyc (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by r-obert** [comment]
Ran into the same issue.

**Comment by grasp** [comment]
+1

**Comment by sittitep** [comment]
+1

**Comment by vaz** [comment]
+1

**Comment by tianlitao** [comment]
+1

**Comment by tarnagas** [comment]
see: 
* https://github.com/Homebrew/homebrew-core/issues/4902#issuecomment-247773168
* http://www.rubydoc.info/github/Homebrew/brew/Superenv%3Ano_weak_imports

try to use:

```sh
export HOMEBREW_CCCFG=w
```

**Comment by drbrain** [comment]
rubyc is not packaged for older versions of macOS, please upgrade to 10.12 or build your own rubyc for your old platform (see: https://github.com/pmq20/ruby-packer#building-rubyc-yourself)

**Comment by grosser** [comment]
thx for the clarification!
Would be nice if it failed with "Oxs version 123 is not supported"
