### ISSUE TITLE
Instructions on compiling rubyc yourself?

### ISSUE THREAD

**Issue by stahnma** [pmq20/ruby-packer#19]
Ultimately my goal here is to see if I could cross compile from x86_64 to arm, all while having a single executable. I don't see instructions on building rubyc itself, which may be just a rubyc package of the bin/rubyc command. 

If I wanted this to work with cross compile targets, do you have any hints? 

Also, great work. This is a very cool project.

**Comment by stahnma** [comment]
FWIW, rubyc doesn't compile on Debian 9 on ARM (without cross compiling).

**Comment by ryanstout** [comment]
@stahnma wondering if you got this working?  We could compile on our arm board directly if needed.

**Comment by drbrain** [comment]
I added a Rakefile and some build instructions to the README ↑

Please open a new issue if you find problems.
