### ISSUE TITLE
Windows Server 2016 Bison not found

### ISSUE THREAD

**Issue by stahnma** [pmq20/ruby-packer#21]
When trying to use rubyc to build a Windows binary, it errors out saying it's looking for bison. I *think* I followed the instruction in the README, with installation of squashfs, visual studio and ruby via ruby-installer. What's the recommended method for getting bison on Windows? (Sorry, I'm minimally proficient on Windows). Do I need something like mingw?

**Comment by r-obert** [comment]
For getting bison and other packages easily on Windows, try https://chocolatey.org/, then: `choco.exe install winflexbison`. 
See https://chocolatey.org/packages?q=bison

**Comment by stahnma** [comment]
Thanks. That appears to work, after ranaming win_bison to bison.

**Comment by r-obert** [comment]
Cool. There could be other packages with GNU Bison, too.
