### ISSUE TITLE
cross-compile instructions ?

### ISSUE THREAD

**Issue by grosser** [pmq20/ruby-packer#26]
Is it possible to compile linux from mac or get a universal binary ...
otherwise saying so in the readme would be nice `binaries will only work on the systems they were compiled on`

**Comment by drbrain** [comment]
It is possible but maintaining a cross-compilation environment is extremely difficult and I don't want the support burden.

You can run rubyc on travis CI to build macOS and Linux binaries that are uploaded to a destination of your choice, and travis CI has a paid option if you need the source and destination to be secret.
