### ISSUE TITLE
Pass official tests

### ISSUE THREAD

**Issue by pmq20** [pmq20/ruby-packer#3]
https://travis-ci.org/ruby/ruby

https://ci.appveyor.com/project/ruby/ruby/branch/trunk

**Comment by dread-uo** [comment]
Hello, pmq20!

I'd like to add those tests again. Why were they abandoned? You think they are unneeded, or making them work was just too troublesome?

**Comment by pmq20** [comment]
@dread-uo Thanks for spotting this! It would be best that we could add the official tests. I had limited time to work on this so I temporarily closed this. Let me reopen it.

**Comment by dread-uo** [comment]
Thanks for the quick reply! I'll get the tests running on Travis. I'm not familiar with windows powershell scripting, so I think I can't make the appveyor tests work, though.

**Comment by dread-uo** [comment]
I've got Travis running the tests, and it works just as locally :smile: 
But the test is failing. It looks for a `ruby` folder on `/tmp/rubyc/`, but this folder doesn't exist - on my machine it is `ruby-2.4.1-0.5.0`, and the one on the travis vm must have that version part that the tests are ignoring, and thus, failing.
