### ISSUE TITLE
README.md: provide instructions for projects using Gemfile and bundle exec

### ISSUE THREAD

**Issue by Nowaker** [pmq20/ruby-packer#71]
I've read README.md and browsed tickets but it's still not clear to me how to pack a Gemfile-based project with its all dependencies, when the project is started using `bundle exec xxx`.

~~~Please note the provided [Rails example](https://github.com/pmq20/ruby-packer#compiling-a-rails-application) isn't a Gemfile/bundler-based project. Calling `bin/rails` bypasses Bundler, risking the packaged application to not be equal to what would run using `bundle exec rails`.~~~ (This must have changed at some point)

**Comment by Erol** [comment]
`bin/rails` doesn't bypass Bundler by default. The dependencies from the Gemfile are configured and loaded via Bundler on `config/boot.rb` and `config/application.rb`

**Comment by Nowaker** [comment]
@Erol Ah, okay. I must have missed the change at some point, and used `bundle exec rails` for years. Anyway, ignoring the Rails example, how does one bundle a generic Gemfile-based project, with no binstubs like `bin/rails` inside the project directory? One that is ran using `bundle exec xxx`.

**Comment by Nowaker** [comment]
Ah. So `# Put your command to run here` would become `load Gem.bin_path('sidekiq', 'sidekiq')` (in general: `load Gem.bin_path(gem_name, binary_name)`).

And to be able to run multiple binstubs, we'd need something like `load Gem.bin_path(ARGV[0], ARGV[0])`, and that assumes the binary name equals the gem name (most cases).

Thanks for your help @Erol. I'll give all this a try, and maybe even come up with a PR to the docs.
