### ISSUE TITLE
Upgrade Ruby from 2.5.1 to 2.7.1

### ISSUE THREAD

**Issue by pmq20** [pmq20/ruby-packer#92]

**Comment by pmq20** [comment]
https://github.com/pmq20/ruby-packer/commit/20110bdfe7916a259f1fad4ea8530abf08d9a981

**Comment by d4rky-pl** [comment]
@pmq20 Is there going to be an official 2.7.1 release binary or should we compile it ourselves from now on? :)

**Comment by pmq20** [comment]
@d4rky-pl Sorry for the delayed Reply. I'm maintaining this project only during the weekend recently. Yes there will be an official 2.7.1 release. I am fixing a lot of issues and run a lot of tests to make sure that this is a good release; so it might take some time. For details, see https://github.com/pmq20/ruby-packer/blob/master/CHANGELOG.md
