### ISSUE TITLE
Not able to run with gems outside of Rubygems (gem "xxx", github: "xxx")

### ISSUE THREAD

**Issue by siccous** [pmq20/ruby-packer#95]
Hello,

I am trying to pack a small project, but it seems to be not working with gems which are not used from RubyGems.

First, I am using current master version of ruby-packer.

In my Gemfile I have this line:
gem "active_directory", github: "w0de/active_directory"
(and other gems, but not from GitHub)

And my entrance script begins with:
require "rubygems"
require "bundler/setup"

When I try to run the packed executable then it ends with "double free or corruption" or similiar error.

I've tried to see what happens exactly with strace and it fails with this line:
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.7.0/bundler/gems/active_directory-b565bdf2e816/.gemspec No such file or directory

When I switch this particular gem to the Rubygems version (which is outdated, that's why using the GitHub version) then it works as expected and the resulting executable can be started.

**Comment by pmq20** [comment]
Thank you for reporting! I have reproduced the error
```
double free or corruption (!prev)
```
